<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="28013" started-at="2020-08-16T09:09:56Z" finished-at="2020-08-16T09:10:24Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:cucumber.Options.TestRunner@66d2e7d9]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="28013" started-at="2020-08-16T09:09:56Z" finished-at="2020-08-16T09:10:24Z">
      <class name="restAPITesting.ApttusStationAPIValidation">
        <test-method status="PASS" signature="registerWeatherWithoutAPIKey()[pri:1, instance:restAPITesting.ApttusStationAPIValidation@1efbd816]" name="registerWeatherWithoutAPIKey" duration-ms="2046" started-at="2020-08-16T09:10:19Z" finished-at="2020-08-16T09:10:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerWeatherWithoutAPIKey -->
        <test-method status="PASS" signature="registerTwoStationsWithValidKey()[pri:2, instance:restAPITesting.ApttusStationAPIValidation@1efbd816]" name="registerTwoStationsWithValidKey" duration-ms="967" started-at="2020-08-16T09:10:21Z" finished-at="2020-08-16T09:10:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTwoStationsWithValidKey -->
        <test-method status="PASS" signature="getStations()[pri:3, instance:restAPITesting.ApttusStationAPIValidation@1efbd816]" name="getStations" duration-ms="486" started-at="2020-08-16T09:10:22Z" finished-at="2020-08-16T09:10:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getStations -->
        <test-method status="PASS" signature="DeleteStations()[pri:4, instance:restAPITesting.ApttusStationAPIValidation@1efbd816]" name="DeleteStations" duration-ms="932" started-at="2020-08-16T09:10:22Z" finished-at="2020-08-16T09:10:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteStations -->
        <test-method status="PASS" signature="verifyStationNotFound()[pri:5, instance:restAPITesting.ApttusStationAPIValidation@1efbd816]" name="verifyStationNotFound" duration-ms="523" started-at="2020-08-16T09:10:23Z" finished-at="2020-08-16T09:10:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStationNotFound -->
      </class> <!-- restAPITesting.ApttusStationAPIValidation -->
      <class name="cucumber.Options.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:cucumber.Options.TestRunner@66d2e7d9]" name="setUpClass" is-config="true" duration-ms="175" started-at="2020-08-16T09:09:56Z" finished-at="2020-08-16T09:09:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:cucumber.Options.TestRunner@66d2e7d9]" name="feature" duration-ms="22749" started-at="2020-08-16T09:09:56Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2020-08-16T09:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Successful Login]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [Orange, S1] but found [Orange, S]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Orange, S1] but found [Orange, S]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.AssertionError: expected [Orange, S1] but found [Orange, S]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pageObjects.ProductValidation.productValidation(ProductValidation.java:55)
at stepDefinations.StepDefination.user_validates_that_the_product_is_successfully_added_to_the_cart(StepDefination.java:86)
at âœ½.And user validates that the product is successfully added to the cart(login.feature:13)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:cucumber.Options.TestRunner@66d2e7d9]" name="tearDownClass" is-config="true" duration-ms="36" started-at="2020-08-16T09:10:19Z" finished-at="2020-08-16T09:10:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- cucumber.Options.TestRunner -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
